(0.1, 128, 5), 
(0.1, 128, 5), 
(0.1, 128, 5), 
(0.1, 128, 5), 
(0.1, 128, 5), 
(0.1, 128, 5), object of type 'int' has no len()
(0.1, 128, 5), Graph execution error:

Detected at node 'StatefulPartitionedCall_10' defined at (most recent call last):
    File "/home/jtrull/python/alzheimers/.tox/py37/bin/pytest", line 8, in <module>
      sys.exit(console_main())
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 185, in console_main
      code = main()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 163, in main
      config=config
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
      return wrap_session(config, _main)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
      session.exitstatus = doit(config, session) or 0
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 323, in _main
      config.hook.pytest_runtestloop(session=session)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
      item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
      runtestprotocol(item, nextitem=nextitem)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 126, in runtestprotocol
      reports.append(call_and_report(item, "call", log))
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 215, in call_and_report
      call = call_runtest_hook(item, when, **kwds)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 255, in call_runtest_hook
      lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 311, in from_call
      result: Optional[TResult] = func()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 255, in <lambda>
      lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 162, in pytest_runtest_call
      item.runtest()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/unittest.py", line 321, in runtest
      self._testcase(result=self)  # type: ignore[arg-type]
    File "/home/jtrull/anaconda3/envs/tf/lib/python3.7/unittest/case.py", line 676, in __call__
      return self.run(*args, **kwds)
    File "/home/jtrull/anaconda3/envs/tf/lib/python3.7/unittest/case.py", line 628, in run
      testMethod()
    File "/home/jtrull/python/alzheimers/tests/tests.py", line 20, in test_train_model
      percent_of_data=0.1, num_epochs=5, batch_size=128, learning_rate=0.01
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/alz_mri_cnn/model_training.py", line 139, in train_model
      callbacks=[callbacks],
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
      self.apply_gradients(grads_and_vars)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1169, in _internal_apply_gradients
      grads_and_vars,
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1217, in _distributed_apply_gradients_fn
      var, apply_grad_to_update_var, args=(grad,), group=False
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_10'
libdevice not found at ./libdevice.10.bc
	 [[{{node StatefulPartitionedCall_10}}]] [Op:__inference_train_function_2240]
(0.1, 128, 5), Graph execution error:

Detected at node 'StatefulPartitionedCall_10' defined at (most recent call last):
    File "/home/jtrull/python/alzheimers/.tox/py37/bin/pytest", line 8, in <module>
      sys.exit(console_main())
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 185, in console_main
      code = main()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 163, in main
      config=config
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
      return wrap_session(config, _main)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
      session.exitstatus = doit(config, session) or 0
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 323, in _main
      config.hook.pytest_runtestloop(session=session)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
      item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
      runtestprotocol(item, nextitem=nextitem)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 126, in runtestprotocol
      reports.append(call_and_report(item, "call", log))
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 215, in call_and_report
      call = call_runtest_hook(item, when, **kwds)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 255, in call_runtest_hook
      lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 311, in from_call
      result: Optional[TResult] = func()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 255, in <lambda>
      lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 162, in pytest_runtest_call
      item.runtest()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/unittest.py", line 321, in runtest
      self._testcase(result=self)  # type: ignore[arg-type]
    File "/home/jtrull/anaconda3/envs/tf/lib/python3.7/unittest/case.py", line 676, in __call__
      return self.run(*args, **kwds)
    File "/home/jtrull/anaconda3/envs/tf/lib/python3.7/unittest/case.py", line 628, in run
      testMethod()
    File "/home/jtrull/python/alzheimers/tests/tests.py", line 20, in test_train_model
      percent_of_data=0.1, num_epochs=5, batch_size=128, learning_rate=0.01
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/alz_mri_cnn/model_training.py", line 139, in train_model
      callbacks=[callbacks],
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
      self.apply_gradients(grads_and_vars)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1169, in _internal_apply_gradients
      grads_and_vars,
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1217, in _distributed_apply_gradients_fn
      var, apply_grad_to_update_var, args=(grad,), group=False
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_10'
libdevice not found at ./libdevice.10.bc
	 [[{{node StatefulPartitionedCall_10}}]] [Op:__inference_train_function_2240]
(0.1, 128, 5), Graph execution error:

Detected at node 'StatefulPartitionedCall_10' defined at (most recent call last):
    File "/home/jtrull/python/alzheimers/.tox/py37/bin/pytest", line 8, in <module>
      sys.exit(console_main())
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 185, in console_main
      code = main()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 163, in main
      config=config
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
      return wrap_session(config, _main)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
      session.exitstatus = doit(config, session) or 0
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 323, in _main
      config.hook.pytest_runtestloop(session=session)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
      item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
      runtestprotocol(item, nextitem=nextitem)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 126, in runtestprotocol
      reports.append(call_and_report(item, "call", log))
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 215, in call_and_report
      call = call_runtest_hook(item, when, **kwds)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 255, in call_runtest_hook
      lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 311, in from_call
      result: Optional[TResult] = func()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 255, in <lambda>
      lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
      return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
      res = hook_impl.function(*args)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 162, in pytest_runtest_call
      item.runtest()
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/_pytest/unittest.py", line 321, in runtest
      self._testcase(result=self)  # type: ignore[arg-type]
    File "/home/jtrull/anaconda3/envs/tf/lib/python3.7/unittest/case.py", line 676, in __call__
      return self.run(*args, **kwds)
    File "/home/jtrull/anaconda3/envs/tf/lib/python3.7/unittest/case.py", line 628, in run
      testMethod()
    File "/home/jtrull/python/alzheimers/tests/tests.py", line 20, in test_train_model
      percent_of_data=0.1, num_epochs=5, batch_size=128, learning_rate=0.01
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/alz_mri_cnn/model_training.py", line 139, in train_model
      callbacks=[callbacks],
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
      self.apply_gradients(grads_and_vars)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1169, in _internal_apply_gradients
      grads_and_vars,
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1217, in _distributed_apply_gradients_fn
      var, apply_grad_to_update_var, args=(grad,), group=False
    File "/home/jtrull/python/alzheimers/.tox/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_10'
libdevice not found at ./libdevice.10.bc
	 [[{{node StatefulPartitionedCall_10}}]] [Op:__inference_train_function_2240]
